# Generated by Django 3.0.2 on 2020-08-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_model',
            old_name='username',
            new_name='usrname',
        ),
    ]
