# Generated by Django 4.2.3 on 2023-07-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('premium', models.BooleanField(default=False)),
                ('discription', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('background_image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('screen_shot_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_length', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_director', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_actor', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_language', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_type', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_category', models.CharField(blank=True, max_length=100, null=True)),
                ('link_4k', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_1920', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_720', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_4k', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_1920', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_720', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_link', models.TextField(blank=True, max_length=10000, null=True)),
                ('movie_online', models.TextField(blank=True, max_length=1000, null=True)),
                ('torent_link_4k', models.CharField(blank=True, max_length=1000, null=True)),
                ('torent_link_1920', models.CharField(blank=True, max_length=1000, null=True)),
                ('torent_link_720', models.CharField(blank=True, max_length=1000, null=True)),
                ('torent_file_link', models.FileField(blank=True, null=True, upload_to='torent_movie')),
                ('tmvdbid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=1500, null=True)),
                ('discription', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trailer_image')),
                ('image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularMovies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('genre_ids', models.CharField(blank=True, max_length=10000, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10000, null=True)),
                ('original_title', models.CharField(blank=True, max_length=10000, null=True)),
                ('overview', models.CharField(blank=True, max_length=10000, null=True)),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('poster_path', models.CharField(blank=True, max_length=10000, null=True)),
                ('release_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('video', models.BooleanField(default=False, null=True)),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=100)),
                ('vote_count', models.IntegerField(null=True)),
                ('movie_category', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('discription', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('series_length', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField()),
                ('series_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('series_director', models.CharField(blank=True, max_length=200, null=True)),
                ('series_actor', models.CharField(blank=True, max_length=1000, null=True)),
                ('series_language', models.CharField(blank=True, max_length=100, null=True)),
                ('series_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('series_size', models.CharField(blank=True, max_length=100, null=True)),
                ('series_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('series_type', models.CharField(blank=True, max_length=200, null=True)),
                ('series_subscription', models.CharField(blank=True, max_length=700, null=True)),
                ('series_category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('seasons', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('selected_season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.seriesmodel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seasons/')),
                ('trailer', models.CharField(blank=True, max_length=5000, null=True)),
                ('link1', models.CharField(blank=True, max_length=5000, null=True)),
                ('link2', models.CharField(blank=True, max_length=5000, null=True)),
                ('link3', models.CharField(blank=True, max_length=5000, null=True)),
                ('online_link', models.CharField(blank=True, max_length=5000, null=True)),
                ('id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
