# Generated by Django 5.0.1 on 2024-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_popularmovies_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedMovies',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
